### ISSUE TITLE
teams find by the resolvers

### ISSUE THREAD

**Issue by ivanberry** [benawad/slack-clone-server#3]
Thanks for your work, when study with your project, I get stuck and then I find there was little error in project.

where the findAll syntax is an error, which should be:

```javascript
findAll({where: {owner: user.id}})  // return all teams belong to the user
findAll({owner: user.id}) // return all teams in the team table, but not filter for the user
```

But in next chapter, I find the `where` comes. 👍 , the issue should be closed. 🤣

**Comment by benawad** [comment]
No worries, good catch
